### ISSUE TITLE
Doctorine problem/issue, dunno if its from my side or yours.

### ISSUE THREAD

**Issue by xLeonius** [kokspflanze/pserverCMSFull#1]
Hey, I've done everything properly and now I'm tryna' generate the database but I'm getting some weird errors after editing PDOConnection.php and before editing it.
http://prntscr.com/7vuek4

**Comment by kokspflanze** [comment]
hi, the problem is the connection to your sql server. the script can not connect to the server.

**Comment by xLeonius** [comment]
Well, I've fixed it, I've kept trying to type proper connection info and eventually i found out that it requires mysql. But now I'm facing another issue, when I type localhost/pservercmsfull in google chrome I get this : http://prntscr.com/7vuu4x

**Comment by xLeonius** [comment]
Didn't try it in the other browsers since I have only google chrome.

**Comment by kokspflanze** [comment]
you can also use mssql for web db.

localhost/pservercmsfull/public, you have to call that in your browser, you can also change the doc root like i wrote it in the tut

**Comment by xLeonius** [comment]
Ok, I've finally managed to get it working. but now I'm getting some errors when I try to surf localhost.
http://prntscr.com/7vzfq7
http://prntscr.com/7vzftx
http://prntscr.com/7vzfxc
Can you tell me what should I do to fix this?
I really appreciate your reply. Thanks =)

**Comment by kokspflanze** [comment]
did you `php composer.phar update` ?

it looks like some parts of kokspflanze/small-user missing.

**Comment by xLeonius** [comment]
Thanks for your reply^^ It works now. But check out 46.4.154.11
Register, login, many things else doesn't work, do I have to edit anything else other than the files you mentioned in the tutorial?

**Comment by xLeonius** [comment]
An error occurred during execution; please try again later.

**Comment by kokspflanze** [comment]
did you fix it with the `composer.phar update`?

you can enable the error logging and little debug helper, check https://github.com/kokspflanze/pserverCMSFull/blob/master/config/autoload/sro.example.php#L3-L18

i think you have a error with the mssql connection, maybe wrong username or missing sql driver.

**Comment by xLeonius** [comment]
Well, when I fixed the old error I updated composer.json and my application.config was messed up (I edited it xD) then when i used the original one again the site worked. About my mssql connection, I've just checked it out and its fine.http://prntscr.com/7w07eg
Btw, I've added you on skype, can you accept me so we can contact easier? Skype: aeron.53

**Comment by xLeonius** [comment]
With updating composer.json  I mean adding 2 new things and edited it like this ; http://prntscr.com/7w0ade

**Comment by kokspflanze** [comment]
the config, with sql params looks wrong, you didnt set the sql driver, also in composer.json please use https://github.com/kokspflanze/pserverCMSFull/blob/master/composer.json with dev-master and not ~3.4

**Comment by kokspflanze** [comment]
the main problem was the sql connect, tcp conenction and driver was not set in config.
