### ISSUE TITLE
A problem with donate page.

### ISSUE THREAD

**Issue by craineyo** [kokspflanze/pserverCMSFull#10]

**Comment by craineyo** [comment]
I have a problem with setting up the donation page. Every time I try to donate, the superrewards' wall doesn't appear and I get an error in donation logs saying : Signature is empty, please check your config.
Could you tell me the solution for this please?

**Comment by kokspflanze** [comment]
@craineyo did you overwrite these config https://github.com/kokspflanze/PServerCore/blob/master/config/module.config.php#L736

with your signature?

if you get again this problem, please enable the debugger and check your merged config @ the debugger toolbar.

**Comment by craineyo** [comment]
Yea thank you it's working now. The problem was with superrewards or so, our wall wasn't working and we had to change it.
