### ISSUE TITLE
How to enable E-mail verifications?

### ISSUE THREAD

**Issue by craineyo** [kokspflanze/pserverCMSFull#11]
I'd like to know how to enable e-mail verification because it's kinda complicated xD

**Comment by kokspflanze** [comment]
you have to set this config to `true`

https://github.com/kokspflanze/PServerCore/blob/master/config/module.config.php#L427

**Comment by craineyo** [comment]
Thank you ;) I installed pservercmsfull so I don't have this file. Can I find it somewhere in PserverCMSFull or should I install pservercore with pservercmsfull?

**Comment by kokspflanze** [comment]
@craineyo its already install you just have to overwrite the config, and dont forget to setup the mail smtp access.
