### ISSUE TITLE
Exception occured

### ISSUE THREAD

**Issue by craineyo** [kokspflanze/pserverCMSFull#13]
An error occurred
An error occurred during execution; please try again later.
I get this whenever I try to open the ranking or register. I checked my sql connection info and it's right :). And also, you told me 1 month ago that you will add unique history but I can't find it now, did you add it or not yet?
Am I able to add SupportOnline?

**Comment by kokspflanze** [comment]
@craineyo can you enable the debugger, to see the error

unique history exist as module but in testing

supportonline is atm not public as module

**Comment by craineyo** [comment]
The error is: Driver not found, How can I solve this?

**Comment by kokspflanze** [comment]
than your setup is not correct, please check the config with the part db connection

**Comment by craineyo** [comment]
I found the error and fixed it =) Thank you =) It was with the mssql required files, I've put x86 dll files in ext directory that's why it wasn't working. I've pt the x64 dll files in ext directory and it works fine now

**Comment by kokspflanze** [comment]
perfect=)
