### ISSUE TITLE
Last questions xD Sorry, I know I'm asking too much

### ISSUE THREAD

**Issue by craineyo** [kokspflanze/pserverCMSFull#14]
Now I am able to see the icons on the website, but can I see the stats? If yes, tell me how to do it xD
And it would be also nice if u could finish the unique history because I need it ^^

**Comment by kokspflanze** [comment]
history you can find @ https://github.com/PServerCMS/SROUnique but its in testing history works also, just  in ranking will be some changes.

about the stats its not added in default ranking, you have to add your own logic or ask other ppl to add these part
