### ISSUE TITLE
Character data error

### ISSUE THREAD

**Issue by elschick** [kokspflanze/pserverCMSFull#15]
Hi ich hab das CMS genau nach anleitung Installiert jedoch bekomme ich eine Fehlermeldung wenn ich auf einen Charname klicke von z.B Player Ranking
http://localhost/ranking/character-6694.html

An error occurred during execution; please try again later.

Was könnte das sein hab ich was vergessen?

**Comment by kokspflanze** [comment]
please enable the debugger, to see the error, like in guide section written.

i think the problem is the OnlineOffline in logs is missing.

**Comment by kokspflanze** [comment]
@elschick problem solved?
