### ISSUE TITLE
Ranking error - conversion failed when converting date and/or time from character string

### ISSUE THREAD

**Issue by craineyo** [kokspflanze/pserverCMSFull#16]
I'm getting the following error when opening ranking.
An exception occurred while executing 'SELECT t0_.UserJID AS UserJID_0 FROM _BlockedUser t0_ WHERE t0_.timeEnd >= ? GROUP BY t0_.UserJID' with params ["2017-07-29 19:41:42.644175"]:

SQLSTATE[22007]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Conversion failed when converting date and/or time from character string.

**Comment by kokspflanze** [comment]
looks like in your blockeduser table is the  timeend col not datetime, please change it than it works

**Comment by craineyo** [comment]
http://epvpimg.com/wxCRcab

It's datetime already

**Comment by kokspflanze** [comment]
is there wrong data stored in the table?
maybe you can clean the table and check it again.

other way could be check the settings for default datetime cast, if that format is correct.
if all not work please send me a screen of the data in your table, the mssql version and the setting info.

**Comment by craineyo** [comment]
I cleaned the table still getting the same error.
http://epvpimg.com/2hR0dab
Here is a screenshot of the contents that were in the table before cleaning it.
My mssql version is 2014 enterprise, what do you mean with check the settings for default datetime cast? The format is the original one which comes with sql 2014, I haven't messed with it.

**Comment by craineyo** [comment]
I solved this by making the format of timeEnd datetime2 instead of datetime. Will see if globalmanager will be able to read this or not later when I restart the server. Meanwhile please try to find a solution for this :)

**Comment by kokspflanze** [comment]
you are the first person with that problem, i tested this with 2012 and 2016, no problems there.
it works also live on some servers.
