### ISSUE TITLE
Would like to have item stats/points at my ranking, how much would it cost?

### ISSUE THREAD

**Issue by craineyo** [kokspflanze/pserverCMSFull#17]
As the title says, I wanna know the prices of the features mentioned in the title. Would you please tell me the prices and give me your discord id?

**Comment by kokspflanze** [comment]
discord kokspflanze, but atm in vacation so response can take a bit time

**Comment by craineyo** [comment]
can't find ur discord

**Comment by kokspflanze** [comment]
KoKsPfLaNzE#1926
