### ISSUE TITLE
openssl

### ISSUE THREAD

**Issue by bibifr** [kokspflanze/pserverCMSFull#18]
hello,
Maybe i have did something wrong and can you tell me what did i have do but i could not found it myself for this time :(

![sans titre](https://user-images.githubusercontent.com/9522188/48276842-4e2b3480-e449-11e8-9c5e-751dc8e8fdc8.png)

Thanks you :)

**Comment by kokspflanze** [comment]
you found the problem?
opensll extension was not enabled in your php.ini

**Comment by bibifr** [comment]
yep i found solution but got a another problem 

![sans titre](https://user-images.githubusercontent.com/9522188/48285323-8c811d80-e462-11e8-9486-7f38f7fb4920.png)

**Comment by kokspflanze** [comment]
can you join the gitter chat? https://gitter.im/kokspflanze/PServerCMS
its faster, btw looks like your php version is bit old

**Comment by kokspflanze** [comment]
chat moved to gitter
