### ISSUE TITLE
An issue

### ISSUE THREAD

**Issue by xLeonius** [kokspflanze/pserverCMSFull#2]
I installed the pservercms and it is working but there is a problem with zend-mvc, it gives me an error says deprecated. Could you please update the zend-mvc files>

**Comment by kokspflanze** [comment]
it is in progress

**Comment by xLeonius** [comment]
Ok, good. When will it be fixed?

**Comment by kokspflanze** [comment]
hope next week, check my commits i done that for the most modules, but not done
and yeah i read your issue at zend-mvc^^

**Comment by xLeonius** [comment]
Cool ^^ could you please check the solution which weierphonie gave me? It should work. He gave me a lot of solutions but I can't do any of them because I',m not really good in CMS or php.
Do you mean that your last commit should mask this problem? I tried it already, I made git pull, php composer.phar update and self update but this didn't hide the problem

**Comment by kokspflanze** [comment]
no the problem comes with zend-mvc 2.7, they set the old workflow on deprrcated so it must be changed now everything to the factory system or the lacy_service systen and in that i work atm, but its a lot of work

**Comment by xLeonius** [comment]
take your time, I disabled error log temporarily until you fix it ^^ it works well now.

Uebrigens, ich kann ein bisschen Deutsch sprechen und schreiben. Du kannst mir alles auf Deutsch erklaeren und ich werde verstehen xD

**Comment by kokspflanze** [comment]
enable the debug-system

maybe problems with mssql connect or a extension missing

**Comment by xLeonius** [comment]
Ok, I will try to fix it. The last questions I have are:
1- How to change the sliders? What is their path?
2- How to change the web title?
3- How to change the background colour? 

Thank you for your help and being kind :)

**Comment by kokspflanze** [comment]
you have to change the layout check https://github.com/kokspflanze/pserverCMSFull#how-to-change-the-layout

**Comment by xLeonius** [comment]
This made me only able to change the title. However, after searching for a long time, I found a way to change the sliders. Now I would like to change the background color to black. Could you please tell me how? The custom layout doesn't contain something like this

**Comment by kokspflanze** [comment]
add in your custome layout a new css file and change it there.

**Comment by kokspflanze** [comment]
should be fixed with https://github.com/kokspflanze/PServerCore/releases/tag/0.4
