### ISSUE TITLE
Cant create Database

### ISSUE THREAD

**Issue by Sybtek** [kokspflanze/pserverCMSFull#3]
![screenshot_3](https://cloud.githubusercontent.com/assets/17151165/13984187/e9511dee-f0f4-11e5-9b99-62c01aaa06c5.png)

also got problem while creating database.

**Comment by kokspflanze** [comment]
is that problem on a mysql db or mssql db?

**Comment by Sybtek** [comment]
i work with mssql db. database is created now and works but not correct. when i try to register an account the webpage shows me an error.
in the database is no account created...
![1](https://cloud.githubusercontent.com/assets/17151165/14004705/5ede1208-f15c-11e5-8397-0aa041a28fa3.png)
![2](https://cloud.githubusercontent.com/assets/17151165/14004704/5eddc49c-f15c-11e5-8217-02ead08aead9.png)
![3](https://cloud.githubusercontent.com/assets/17151165/14004703/5edd7d3e-f15c-11e5-9f16-a02f7e304b8f.png)

idk what happend. i installed pserver cms 3 month befor and it was running well without any errors like that. i did the installation like befor. but now there many problems...

**Comment by kokspflanze** [comment]
i will test today the webdb with a mssql server.

in last 3 month was many updates, but only tested with mysql server (maria-db)

**Comment by Sybtek** [comment]
ok then i will wait for ur replay. im a bit confused bc i installed pserver cms save way then 1 month ago. befor everything works fine, but after 1 month and new installation there are much problems with unknown reason....

**Comment by kokspflanze** [comment]
the main problem is https://github.com/doctrine/dbal/issues/1002

dblib and DBAL,

you can do that in the vendor file for testing:
https://github.com/kokspflanze/PServerCore/commit/b6f528f2eca46e3ce2415191e9f6648c4c20ee8e

but i real recommended to use a mysql server, for db-updates and better integration/performance on a remote linux webserver

**Comment by Sybtek** [comment]
hmm but why i worked 4 weeks ago? there was no problem like that... did u made any changes this time? that really sucks... i never worked with mysql.

**Comment by kokspflanze** [comment]
in last version was no unique, i removed it now
see https://github.com/kokspflanze/PServerCore/releases/tag/0.4.2

**Comment by Sybtek** [comment]
so what that mean?

**Comment by kokspflanze** [comment]
drop the current database and update the files with composer

or

delete the unique on user.username

**Comment by Sybtek** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/17151165/14093014/151f3848-f54b-11e5-8f77-bcc7f0249fcf.png)
still cant create database

**Comment by kokspflanze** [comment]
the mssql db was clean?
can you run the command directly in mssql, so i can see the error message, for me i tested it on mssql 2012

**Comment by Sybtek** [comment]
yes database was clean. i use mssql 2014 and still cant create database. so whats the solution for that?

**Comment by kokspflanze** [comment]
did you try the command in the message directly in mssql?
i need the error of this message

**Comment by Sybtek** [comment]
![screenshot_2](https://cloud.githubusercontent.com/assets/17151165/14105202/5e8a0c06-f5aa-11e5-9054-34619bc99aac.png)

**Comment by kokspflanze** [comment]
so everything runs?
and you can work with the page?

**Comment by Sybtek** [comment]
no still not work. idk what u changed last time. i did everything like my last setup where everything works fine. but now nothing works like befor.

**Comment by kokspflanze** [comment]
what is not working? error message? i need some informations.

**Comment by Sybtek** [comment]
[Tue Mar 29 12:39:39.594391 2016] [:error] [pid 10687] [client xxxxxxxxxx:2126] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 208 General SQL Server error: Check messages from the SQL Server [208] (severity 16) [SELECT t0.id AS id_1, t0.role_id AS role_id_2, t0.is_default AS is_default_3, t0.parent_id AS parent_id_4 FROM user_role t0]' in /var/www/html/pserverCMSFull/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104\nStack trace:\n#0 /var/www/html/pserverCMSFull/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(104): PDO->query('SELECT t0.id AS...')\n#1 /var/www/html/pserverCMSFull/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(833): Doctrine\\DBAL\\Driver\\PDOConnection->query('SELECT t0.id AS...')\n#2 /var/www/html/pserverCMSFull/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(884): Doctrine\\DBAL\\Connection->executeQuery('SELECT t0.id AS...', Array, Array)\n#3 /var/www/html/pserverCMSFull/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php(181): Doctrine\\ORM\\Persisters\\Entity\\BasicEnt in /var/www/html/pserverCMSFull/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php on line 119


on apache2 logs i found this

**Comment by kokspflanze** [comment]
the table exists?
please run `SELECT t0.id AS id_1, t0.role_id AS role_id_2, t0.is_default AS is_default_3, t0.parent_id AS parent_id_4 FROM user_role t0` directly on mssql, so you see the full message

**Comment by Sybtek** [comment]
back again.
i got the page work now. but it was really hard...
but now there is an new problem...
u can register on the page and it say success u can log in now.
BUT....
u can only log in on webpage. it create an account on  pserverCMS2 database but not on SRO_ACCOUNT database....

**Comment by kokspflanze** [comment]
so i can close it?

**Comment by Sybtek** [comment]
yes but there are some other questions like what sould i do to show online players on webpage.... ?

**Comment by kokspflanze** [comment]
you have to setup the [crons](https://github.com/kokspflanze/PServerCMS#crontab-settings)

**Comment by Sybtek** [comment]
sry dont understand what to do with crons... can u explain it a bit better?

**Comment by kokspflanze** [comment]
check [How do I set up a Cron job?](http://askubuntu.com/questions/2368/how-do-i-set-up-a-cron-job)

**Comment by Sybtek** [comment]
any db entry needed? if yes  can u post an screen how the db must look

**Comment by kokspflanze** [comment]
you need the _OnlineOffline table in your Log DB like [this](https://github.com/kokspflanze/GameBackend/blob/master/src/GameBackend/Entity/SRO/Log/OnlineOffline.php)

**Comment by Sybtek** [comment]
well... db is done but i still cant see online players bc i do not understand what to do with that cron thing.

**Comment by kokspflanze** [comment]
i send you a guide, where you can find informations about that, what you not understand?

**Comment by Sybtek** [comment]
hi again. i i tryed to make that shit with cron job but it stil not works. can u make an guide how to show online players plz. i tryed everything but it wont work.

**Comment by Sybtek** [comment]
not everybody is an spezialist. much ppl do that for an hobby.

**Comment by kokspflanze** [comment]
[guide](http://www.cyberciti.biz/faq/how-do-i-add-jobs-to-cron-under-linux-or-unix-oses/)

so `crontab -e` (the easy way) and than add the parts i posted, also change it to the right path.

that is nothing special, that are linux basics.
