### ISSUE TITLE
Cant Create MSSQL Database

### ISSUE THREAD

**Issue by elschick** [kokspflanze/pserverCMSFull#4]
Hi i try 3 days now to get it worked :(
first i try it under Plesk with Windows VPS
not worked now i get it half worked with standalone Apache 2.4 
but if i try to create database with mssql i got error in Git Bash:

PHP Fatal error: wrong parameters for Exception([String $exception [, long $code [, Exception $previous = NULL]]]) in c:\Apache2.4\htdocs\pserverCMSFull\vendor\zendframework\Zend-servicemanager\src\ServiceManager.php on Line 945

i only change this

'orm_default' => [
                // mssql db @ windows  => 'GameBackend\DBAL\Driver\PDOSqlsrv\Driver'
                // mssql db @ linux  => 'GameBackend\DBAL\Driver\PDODblib\Driver',
                'driverClass' =>'GameBackend\DBAL\Driver\PDOSqlsrv\Driver',

                'params' => [
                    'host'     => '62.138.3.183',
                    'port'     => '1443',
                    'user'     => 'sa',
                    'password' => 'xxxxxx',
                    'dbname'   => 'pserverCMS',
                ],

**Comment by kokspflanze** [comment]
@elschick 
is your mssql running on port 1443?

default is 1433 check also if you added `extension=php_pdo_sqlsrv_56_ts.dll` in your php.ini and if its working

**Comment by elschick** [comment]
Hi i installed Now ODBC Driver 11 this error now fixed but now it dont connect to sql server odbc connect error


Mit freundlichen GrüßenH.Schick-------- Ursprüngliche Nachricht --------Von: Oliver <notifications@github.com> Datum: 23.08.2016  14:15  (GMT+01:00) An: kokspflanze/pserverCMSFull <pserverCMSFull@noreply.github.com> Cc: elschick <iphone23@gmx.de>, Mention <mention@noreply.github.com> Betreff: Re: [kokspflanze/pserverCMSFull] Cant Create MSSQL Database (#4) 
@elschick 

is your mssql running on port 1443?

default is 1433 check also if you added extension=php_pdo_sqlsrv_56_ts.dll in your php.ini and if its working

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/kokspflanze/pserverCMSFull","title":"kokspflanze/pserverCMSFull","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/kokspflanze/pserverCMSFull"}},"updates":{"snippets":[{"icon":"PERSON","message":"@kokspflanze in #4: @elschick \r\nis your mssql running on port 1443?\r\n\r\ndefault is 1433 check also if you added `extension=php_pdo_sqlsrv_56_ts.dll` in your php.ini and if its working"}],"action":{"name":"View Issue","url":"https://github.com/kokspflanze/pserverCMSFull/issues/4#issuecomment-241712062"}}}

**Comment by kokspflanze** [comment]
there is a gitter chat =)

https://gitter.im/kokspflanze/PServerCMS?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge
