### ISSUE TITLE
Admin Panel problem

### ISSUE THREAD

**Issue by Vaatu** [kokspflanze/pserverCMSFull#7]
when i go to admin panel i get this 
![image](https://cloud.githubusercontent.com/assets/20728999/21573062/fe8f75f2-cee8-11e6-9435-31405f12d5bb.png)

**Comment by kokspflanze** [comment]
there is a guide for this problem http://support.gnip.com/articles/curl-on-win7.html

i created a task also https://github.com/kokspflanze/PServerAdmin/issues/3 to create a workarround for this

**Comment by kokspflanze** [comment]
@Vaatu also added in guide https://github.com/kokspflanze/pserverCMSFull/blob/master/doc/windows-setup/APACHE.md#curl-cainfo-optional
