### ISSUE TITLE
online players 

### ISSUE THREAD

**Issue by great4ever** [kokspflanze/pserverCMSFull#8]
the site cant read how many players online can you help

**Comment by kokspflanze** [comment]
@great4ever did you added the crons? https://github.com/kokspflanze/PServerCMS#crontab-settings

**Comment by great4ever** [comment]
sorry iam really new at this stuff so where can i add them

**Comment by kokspflanze** [comment]
@great4ever on which os did you setup the page? on centos its automatic added in the install script. windows just google  how to setuo crons. like https://piwik.org/docs/setup-auto-archiving/#windows-how-to-set-up-auto-archiving-using-windows-scheduler
