### ISSUE TITLE
Admin Error with github

### ISSUE THREAD

**Issue by Dru99** [kokspflanze/pserverCMSFull#9]
I have Error shown into the admin panel : 
You have reached GitHub hourly limit! Actual limit is: 60

**Comment by kokspflanze** [comment]
the default config should enable the caching, the guides on centos set the permissions to the correct part, so i see no problem to change it =)

thanks=)

**Comment by kokspflanze** [comment]
done with https://github.com/kokspflanze/PServerCore/commit/c01539bf781e10df35a5c74dba2341c55620ac8f
